# AWS account ID of the environment
account-id: 052077505538


# Log Retention days in Cloudwatch
log-retention: 30

#Security groups for the functions
securityGroupIds:
  - sg-04b3e9057d69dc801

#VPC APP subnet under which function should run
subnetIds:
  - subnet-09b66829ef9884152
  - subnet-07bb7d515b3b2fdbe

restApiId: n2c8vrhhui

restApiRootResourceId: 4m2rf3zxre

#restApiResourceID: 5va5wu

#stylenameRestApiResourceID: 1n89ak

#versionRestApiResourceID: zaiukb

#envRestApiResourceID: ovrx82

# All environment variables should go in here
# Standard fields  
#   - CTP-ENV	
#  - CTP-REGION
#  - LOGGER_LEVEL
# Optional fields
#  - CTP-APP-SECRET
# All app specific env variables can go here e.g. TOMTOM_ENDPOINT
env-vars:
  APP_ENVIRONMENT: prod
  REGION: us-east-1
  LOGGER_LEVEL: debug
  CLOUD_WATCH_LOG_GROUP_NAME : /aws/lambda/prod-us-east-1-navi-mapbox-service-audit
  MAPBOX_ENDPOINT: https://api.mapbox.com/tokens/v2/
  MAPBOX_ACCOUNT_TABLE : prod-global-navi-admin-mapbox-account
  MAP_STYLE_INFO_TABLE : prod-global-navi-admin-map-style-info
  MAPBOX_STYLE_ENDPOINT : https://api.mapbox.com/styles/v1/
  MAPBOX_FONTS_ENDPOINT : https://api.mapbox.com/fonts/v1/
  MAP_STYLE_VERSIONS_S3_CUCKET : ctp21-prod-us-east-1-navi-adminportal-map-style
  JOB_STATUS_LAMBDA_ARN : arn:aws:lambda:us-east-1:052077505538:function:prod-us-east-1-navi-admin-job-status-updateJobStatus
  GET_MAPBOX_ACCOUNTS_FUNCTION_NAME : prod-us-east-1-navi-admin-mapbox-account-getMapboxAccounts
